### ISSUE TITLE
spark 2.1.0 write RDD to kafka

### ISSUE THREAD

**Issue by yodagast** [BenFradet/spark-kafka-writer#93] opened 2018-03-22 08:14 UTC
I was use Spark 2.1.0 write RDD to Kafka,then I get this error

18/03/22 15:57:00 INFO TaskSetBlacklist: Blacklisting executor 1 for stage 1
18/03/22 15:57:00 INFO YarnScheduler: Cancelling stage 1
18/03/22 15:57:00 INFO YarnScheduler: Stage 1 was cancelled
18/03/22 15:57:00 INFO DAGScheduler: ResultStage 1 (foreachPartition at RDDKafkaWriter.scala:48) failed in 1.953 s due to Job aborted due to stage failure: Aborting TaskSet 1.0 because task 999 (partition 999) cannot run anywhere due to node and executor blacklist.  Blacklisting behavior can be configured via spark.blacklist.*.
18/03/22 15:57:00 INFO DAGScheduler: Job 1 failed: foreachPartition at RDDKafkaWriter.scala:48, took 2.343091 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Aborting TaskSet 1.0 because task 999 (partition 999) cannot run anywhere due to node and executor blacklist.  Blacklisting behavior can be configured via spark.blacklist.*.
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)

**Comment by BenFradet** [comment] 2018-03-22 09:12
I think this is caused by the task failing multiple times (which in turn caused node / executor blacklisting) but doesn't contain why it failed, do you have other logs?

**Comment by yodagast** [comment] 2018-03-31 09:15
this seems RDD[ROW] can't be written into Kafka

**Comment by BenFradet** [comment] 2018-03-31 09:31
you should be able to keep a DataFrame and write it to Kafka in this case, no?

**Comment by BenFradet** [comment] 2018-11-13 16:56
no updates, closing

**Closed by BenFradet** 2018-11-13 16:56 UTC
